feat: add allow-overwrite input
qlik-oss/qmfe-actions pull request #56
Opened 2021-11-16 22:13 UTC by chrismanley

2021-11-17 07:40 UTC, egilsster requested changes
We added checks to fail when files existed because overwriting the files burned us in the past. What's your use case? Can you elaborate a bit on this

2021-11-17 13:55 UTC, chrismanley commented
It burned me in particular, so I'm well familiar! 

The use case is for our master branch. We want to have it always building and I don't want to create a unique deploy for it on every single commit. Disallowing overwrite is still the default, this would only be used when explicitly set.

2021-11-17 14:12 UTC, nilzona reviewed
Since this would be a conscious decision to actually allow overwrite I think it's ok for the use case you provided. Normally users will not see this. But maybe make it a bit clearer in the docs that it should just be used if you "know what youi're doing"

2021-11-17 14:12 UTC, nilzona commented on qmfe-to-aws/qmfe-to-aws.sh
> +if [[ $ALLOW_OVERWRITE = "false" ]] && [[ $(aws s3 ls "s3://$AWS_BUCKET_NAME/$S3_KEY/$QMFE_ID/$VERSION" | head) ]]; then
shell script is not like any other language. I think you should use `==` here according to the docs I found here https://linuxize.com/post/how-to-compare-strings-in-bash/

2021-11-17 14:12 UTC, nilzona commented on qmfe-to-aws/action.yaml
> +  allow-overwrite:
perhaps a disclaimer here *WARNING*  or something

2021-11-18 07:24 UTC, egilsster approved these changes

2021-11-18 07:24 UTC, merged